// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: sms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreCost     float32                `protobuf:"fixed32,1,opt,name=storeCost,proto3" json:"storeCost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductMessage) Reset() {
	*x = CreateProductMessage{}
	mi := &file_sms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductMessage) ProtoMessage() {}

func (x *CreateProductMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductMessage.ProtoReflect.Descriptor instead.
func (*CreateProductMessage) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductMessage) GetStoreCost() float32 {
	if x != nil {
		return x.StoreCost
	}
	return 0
}

type UuidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UuidResponse) Reset() {
	*x = UuidResponse{}
	mi := &file_sms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UuidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UuidResponse) ProtoMessage() {}

func (x *UuidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UuidResponse.ProtoReflect.Descriptor instead.
func (*UuidResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{1}
}

func (x *UuidResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UuidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UuidRequest) Reset() {
	*x = UuidRequest{}
	mi := &file_sms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UuidRequest) ProtoMessage() {}

func (x *UuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UuidRequest.ProtoReflect.Descriptor instead.
func (*UuidRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{2}
}

func (x *UuidRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SetProductCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	StoreCost     float32                `protobuf:"fixed32,2,opt,name=storeCost,proto3" json:"storeCost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProductCostRequest) Reset() {
	*x = SetProductCostRequest{}
	mi := &file_sms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProductCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProductCostRequest) ProtoMessage() {}

func (x *SetProductCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProductCostRequest.ProtoReflect.Descriptor instead.
func (*SetProductCostRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{3}
}

func (x *SetProductCostRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SetProductCostRequest) GetStoreCost() float32 {
	if x != nil {
		return x.StoreCost
	}
	return 0
}

type SetProductAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	StoreAmount   float32                `protobuf:"fixed32,2,opt,name=storeAmount,proto3" json:"storeAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProductAmountRequest) Reset() {
	*x = SetProductAmountRequest{}
	mi := &file_sms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProductAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProductAmountRequest) ProtoMessage() {}

func (x *SetProductAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProductAmountRequest.ProtoReflect.Descriptor instead.
func (*SetProductAmountRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{4}
}

func (x *SetProductAmountRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SetProductAmountRequest) GetStoreAmount() float32 {
	if x != nil {
		return x.StoreAmount
	}
	return 0
}

type GetStoreAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreAmount   float32                `protobuf:"fixed32,1,opt,name=storeAmount,proto3" json:"storeAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreAmountResponse) Reset() {
	*x = GetStoreAmountResponse{}
	mi := &file_sms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreAmountResponse) ProtoMessage() {}

func (x *GetStoreAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreAmountResponse.ProtoReflect.Descriptor instead.
func (*GetStoreAmountResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{5}
}

func (x *GetStoreAmountResponse) GetStoreAmount() float32 {
	if x != nil {
		return x.StoreAmount
	}
	return 0
}

type SupplyProductModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid   string                 `protobuf:"bytes,1,opt,name=productUuid,proto3" json:"productUuid,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyProductModel) Reset() {
	*x = SupplyProductModel{}
	mi := &file_sms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyProductModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyProductModel) ProtoMessage() {}

func (x *SupplyProductModel) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyProductModel.ProtoReflect.Descriptor instead.
func (*SupplyProductModel) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{6}
}

func (x *SupplyProductModel) GetProductUuid() string {
	if x != nil {
		return x.ProductUuid
	}
	return ""
}

func (x *SupplyProductModel) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateSupplyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SupplyCost      float32                `protobuf:"fixed32,1,opt,name=supplyCost,proto3" json:"supplyCost,omitempty"`
	DesiredDate     string                 `protobuf:"bytes,2,opt,name=desiredDate,proto3" json:"desiredDate,omitempty"`
	Comment         string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	ResponsibleUser string                 `protobuf:"bytes,4,opt,name=responsibleUser,proto3" json:"responsibleUser,omitempty"`
	Products        []*SupplyProductModel  `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSupplyRequest) Reset() {
	*x = CreateSupplyRequest{}
	mi := &file_sms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSupplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSupplyRequest) ProtoMessage() {}

func (x *CreateSupplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSupplyRequest.ProtoReflect.Descriptor instead.
func (*CreateSupplyRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSupplyRequest) GetSupplyCost() float32 {
	if x != nil {
		return x.SupplyCost
	}
	return 0
}

func (x *CreateSupplyRequest) GetDesiredDate() string {
	if x != nil {
		return x.DesiredDate
	}
	return ""
}

func (x *CreateSupplyRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateSupplyRequest) GetResponsibleUser() string {
	if x != nil {
		return x.ResponsibleUser
	}
	return ""
}

func (x *CreateSupplyRequest) GetProducts() []*SupplyProductModel {
	if x != nil {
		return x.Products
	}
	return nil
}

type UpdateSupplyInfoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Comment         string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	DesiredDate     string                 `protobuf:"bytes,3,opt,name=desiredDate,proto3" json:"desiredDate,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ResponsibleUser string                 `protobuf:"bytes,5,opt,name=responsibleUser,proto3" json:"responsibleUser,omitempty"`
	Cost            float32                `protobuf:"fixed32,6,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSupplyInfoRequest) Reset() {
	*x = UpdateSupplyInfoRequest{}
	mi := &file_sms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSupplyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSupplyInfoRequest) ProtoMessage() {}

func (x *UpdateSupplyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSupplyInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateSupplyInfoRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSupplyInfoRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateSupplyInfoRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *UpdateSupplyInfoRequest) GetDesiredDate() string {
	if x != nil {
		return x.DesiredDate
	}
	return ""
}

func (x *UpdateSupplyInfoRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateSupplyInfoRequest) GetResponsibleUser() string {
	if x != nil {
		return x.ResponsibleUser
	}
	return ""
}

func (x *UpdateSupplyInfoRequest) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type SupplyModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Comment         string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	DesiredDate     string                 `protobuf:"bytes,3,opt,name=desiredDate,proto3" json:"desiredDate,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ResponsibleUser string                 `protobuf:"bytes,5,opt,name=responsibleUser,proto3" json:"responsibleUser,omitempty"`
	Cost            float32                `protobuf:"fixed32,6,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SupplyModel) Reset() {
	*x = SupplyModel{}
	mi := &file_sms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyModel) ProtoMessage() {}

func (x *SupplyModel) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyModel.ProtoReflect.Descriptor instead.
func (*SupplyModel) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{9}
}

func (x *SupplyModel) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SupplyModel) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *SupplyModel) GetDesiredDate() string {
	if x != nil {
		return x.DesiredDate
	}
	return ""
}

func (x *SupplyModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SupplyModel) GetResponsibleUser() string {
	if x != nil {
		return x.ResponsibleUser
	}
	return ""
}

func (x *SupplyModel) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type GetActiveSuppliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supplies      []*SupplyModel         `protobuf:"bytes,1,rep,name=supplies,proto3" json:"supplies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSuppliesResponse) Reset() {
	*x = GetActiveSuppliesResponse{}
	mi := &file_sms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSuppliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSuppliesResponse) ProtoMessage() {}

func (x *GetActiveSuppliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSuppliesResponse.ProtoReflect.Descriptor instead.
func (*GetActiveSuppliesResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{10}
}

func (x *GetActiveSuppliesResponse) GetSupplies() []*SupplyModel {
	if x != nil {
		return x.Supplies
	}
	return nil
}

var File_sms_proto protoreflect.FileDescriptor

const file_sms_proto_rawDesc = "" +
	"\n" +
	"\tsms.proto\x12\x03sms\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\x14CreateProductMessage\x12\x1c\n" +
	"\tstoreCost\x18\x01 \x01(\x02R\tstoreCost\"\"\n" +
	"\fUuidResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"!\n" +
	"\vUuidRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"I\n" +
	"\x15SetProductCostRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\tstoreCost\x18\x02 \x01(\x02R\tstoreCost\"O\n" +
	"\x17SetProductAmountRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12 \n" +
	"\vstoreAmount\x18\x02 \x01(\x02R\vstoreAmount\":\n" +
	"\x16GetStoreAmountResponse\x12 \n" +
	"\vstoreAmount\x18\x01 \x01(\x02R\vstoreAmount\"N\n" +
	"\x12SupplyProductModel\x12 \n" +
	"\vproductUuid\x18\x01 \x01(\tR\vproductUuid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\"\xd0\x01\n" +
	"\x13CreateSupplyRequest\x12\x1e\n" +
	"\n" +
	"supplyCost\x18\x01 \x01(\x02R\n" +
	"supplyCost\x12 \n" +
	"\vdesiredDate\x18\x02 \x01(\tR\vdesiredDate\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12(\n" +
	"\x0fresponsibleUser\x18\x04 \x01(\tR\x0fresponsibleUser\x123\n" +
	"\bproducts\x18\x05 \x03(\v2\x17.sms.SupplyProductModelR\bproducts\"\xbf\x01\n" +
	"\x17UpdateSupplyInfoRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdesiredDate\x18\x03 \x01(\tR\vdesiredDate\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12(\n" +
	"\x0fresponsibleUser\x18\x05 \x01(\tR\x0fresponsibleUser\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x02R\x04cost\"\xb3\x01\n" +
	"\vSupplyModel\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12 \n" +
	"\vdesiredDate\x18\x03 \x01(\tR\vdesiredDate\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12(\n" +
	"\x0fresponsibleUser\x18\x05 \x01(\tR\x0fresponsibleUser\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x02R\x04cost\"I\n" +
	"\x19GetActiveSuppliesResponse\x12,\n" +
	"\bsupplies\x18\x01 \x03(\v2\x10.sms.SupplyModelR\bsupplies2\xc8\x02\n" +
	"\x0eProductService\x12=\n" +
	"\rCreateProduct\x12\x19.sms.CreateProductMessage\x1a\x11.sms.UuidResponse\x124\n" +
	"\rDeleteProduct\x12\x10.sms.UuidRequest\x1a\x11.sms.UuidResponse\x12=\n" +
	"\fSetStoreCost\x12\x1a.sms.SetProductCostRequest\x1a\x11.sms.UuidResponse\x12A\n" +
	"\x0eSetStoreAmount\x12\x1c.sms.SetProductAmountRequest\x1a\x11.sms.UuidResponse\x12?\n" +
	"\x0eGetStoreAmount\x12\x10.sms.UuidRequest\x1a\x1b.sms.GetStoreAmountResponse2\xc8\x02\n" +
	"\rSupplyService\x12;\n" +
	"\fCreateSupply\x12\x18.sms.CreateSupplyRequest\x1a\x11.sms.UuidResponse\x123\n" +
	"\fDeleteSupply\x12\x10.sms.UuidRequest\x1a\x11.sms.UuidResponse\x12C\n" +
	"\x10UpdateSupplyInfo\x12\x1c.sms.UpdateSupplyInfoRequest\x1a\x11.sms.UuidResponse\x12K\n" +
	"\x11GetActiveSupplies\x12\x16.google.protobuf.Empty\x1a\x1e.sms.GetActiveSuppliesResponse\x123\n" +
	"\rGetSupplyById\x12\x10.sms.UuidRequest\x1a\x10.sms.SupplyModelB'Z%github.com/igntnk/stocky-sms/proto/pbb\x06proto3"

var (
	file_sms_proto_rawDescOnce sync.Once
	file_sms_proto_rawDescData []byte
)

func file_sms_proto_rawDescGZIP() []byte {
	file_sms_proto_rawDescOnce.Do(func() {
		file_sms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sms_proto_rawDesc), len(file_sms_proto_rawDesc)))
	})
	return file_sms_proto_rawDescData
}

var file_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sms_proto_goTypes = []any{
	(*CreateProductMessage)(nil),      // 0: sms.CreateProductMessage
	(*UuidResponse)(nil),              // 1: sms.UuidResponse
	(*UuidRequest)(nil),               // 2: sms.UuidRequest
	(*SetProductCostRequest)(nil),     // 3: sms.SetProductCostRequest
	(*SetProductAmountRequest)(nil),   // 4: sms.SetProductAmountRequest
	(*GetStoreAmountResponse)(nil),    // 5: sms.GetStoreAmountResponse
	(*SupplyProductModel)(nil),        // 6: sms.SupplyProductModel
	(*CreateSupplyRequest)(nil),       // 7: sms.CreateSupplyRequest
	(*UpdateSupplyInfoRequest)(nil),   // 8: sms.UpdateSupplyInfoRequest
	(*SupplyModel)(nil),               // 9: sms.SupplyModel
	(*GetActiveSuppliesResponse)(nil), // 10: sms.GetActiveSuppliesResponse
	(*emptypb.Empty)(nil),             // 11: google.protobuf.Empty
}
var file_sms_proto_depIdxs = []int32{
	6,  // 0: sms.CreateSupplyRequest.products:type_name -> sms.SupplyProductModel
	9,  // 1: sms.GetActiveSuppliesResponse.supplies:type_name -> sms.SupplyModel
	0,  // 2: sms.ProductService.CreateProduct:input_type -> sms.CreateProductMessage
	2,  // 3: sms.ProductService.DeleteProduct:input_type -> sms.UuidRequest
	3,  // 4: sms.ProductService.SetStoreCost:input_type -> sms.SetProductCostRequest
	4,  // 5: sms.ProductService.SetStoreAmount:input_type -> sms.SetProductAmountRequest
	2,  // 6: sms.ProductService.GetStoreAmount:input_type -> sms.UuidRequest
	7,  // 7: sms.SupplyService.CreateSupply:input_type -> sms.CreateSupplyRequest
	2,  // 8: sms.SupplyService.DeleteSupply:input_type -> sms.UuidRequest
	8,  // 9: sms.SupplyService.UpdateSupplyInfo:input_type -> sms.UpdateSupplyInfoRequest
	11, // 10: sms.SupplyService.GetActiveSupplies:input_type -> google.protobuf.Empty
	2,  // 11: sms.SupplyService.GetSupplyById:input_type -> sms.UuidRequest
	1,  // 12: sms.ProductService.CreateProduct:output_type -> sms.UuidResponse
	1,  // 13: sms.ProductService.DeleteProduct:output_type -> sms.UuidResponse
	1,  // 14: sms.ProductService.SetStoreCost:output_type -> sms.UuidResponse
	1,  // 15: sms.ProductService.SetStoreAmount:output_type -> sms.UuidResponse
	5,  // 16: sms.ProductService.GetStoreAmount:output_type -> sms.GetStoreAmountResponse
	1,  // 17: sms.SupplyService.CreateSupply:output_type -> sms.UuidResponse
	1,  // 18: sms.SupplyService.DeleteSupply:output_type -> sms.UuidResponse
	1,  // 19: sms.SupplyService.UpdateSupplyInfo:output_type -> sms.UuidResponse
	10, // 20: sms.SupplyService.GetActiveSupplies:output_type -> sms.GetActiveSuppliesResponse
	9,  // 21: sms.SupplyService.GetSupplyById:output_type -> sms.SupplyModel
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_sms_proto_init() }
func file_sms_proto_init() {
	if File_sms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sms_proto_rawDesc), len(file_sms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sms_proto_goTypes,
		DependencyIndexes: file_sms_proto_depIdxs,
		MessageInfos:      file_sms_proto_msgTypes,
	}.Build()
	File_sms_proto = out.File
	file_sms_proto_goTypes = nil
	file_sms_proto_depIdxs = nil
}
